'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random()}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), norm=v=>String(v??'').trim().toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ');
const I18N=window.FOOTBALL_I18N||{}, PLAY_ONLY=!!window.FOOTBALL_PLAY_ONLY;
const POS=[[12,50],[27,20],[27,42],[27,65],[27,82],[48,24],[48,48],[48,72],[70,28],[70,52],[70,76]];
const player=i=>({id:uid(),name:`Игрок ${i+1}`,asset:'',x:POS[i]?.[0]??50,y:POS[i]?.[1]??50});
const question=()=>({id:uid(),type:'single',text:'Какой ответ верный?',options:[{id:uid(),text:'Первый вариант',correct:true},{id:uid(),text:'Второй вариант',correct:false},{id:uid(),text:'Третий вариант',correct:false}],accepted:['Ответ'],hint:'',explanation:'',points:100});
const defaults=()=>({schemaVersion:2,appVersion:'2.0.0',meta:{title:'Мой футбольный урок',author:'Гальмиз Мария Александровна'},locale:'ru',mode:'field',lives:3,timerEnabled:true,timerSeconds:180,soundEnabled:true,reducedMotion:false,publicUrl:'',keeperDifficulty:'normal',media:{fieldBackground:'',keeperBackground:'',keeper:'',goal:''},players:Array.from({length:11},(_,i)=>player(i)),questions:[question()],theme:{accent:'#9cff58',card:'#102a22',text:'#ffffff',button:'#b7f34a',questionSize:28,answerSize:17,cardOpacity:92,mathPreview:true}});
let project=window.FOOTBALL_BOOT_PROJECT?window.FOOTBALL_BOOT_PROJECT:defaults(), activeQ=null, history=[], hi=0, saveTimer;
const G={running:false,ended:false,lives:3,time:180,points:0,goals:0,q:0,active:null,pending:null,task:false,selected:new Set(),order:[],feedback:'',locked:false,aim:null,timer:null};
function tr(k){return (I18N[project.locale]||I18N.en||{})[k]||k}
function ensure(){project={...defaults(),...project};project.meta={...defaults().meta,...project.meta};project.media={...defaults().media,...project.media};project.theme={...defaults().theme,...project.theme};project.players=Array.isArray(project.players)?project.players.slice(0,11):[];while(project.players.length<11)project.players.push(player(project.players.length));project.players.forEach((p,i)=>{p.id||=uid();p.name||=`Игрок ${i+1}`;p.asset||='';if(!Number.isFinite(p.x))p.x=POS[i]?.[0]??50;if(!Number.isFinite(p.y))p.y=POS[i]?.[1]??50});project.questions=Array.isArray(project.questions)?project.questions:[];project.mode=project.mode==='keeper'?'keeper':'field';project.lives=clamp(+project.lives||3,1,20);project.timerSeconds=clamp(+project.timerSeconds||180,15,3600);activeQ=project.questions.some(q=>q.id===activeQ)?activeQ:project.questions[0]?.id||null}
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function math(root=document){if(project.theme.mathPreview===false||typeof renderMathInElement!=='function')return;try{renderMathInElement(root,{delimiters:[{left:'$$',right:'$$',display:true},{left:'\\[',right:'\\]',display:true},{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false}],throwOnError:false,strict:'ignore'})}catch{}}
function changed(render=true){if(PLAY_ONLY)return;$('#saveState').textContent='Есть изменения';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('football-editor-draft-v2',JSON.stringify(project));$('#saveState').textContent='Сохранено локально'}catch{}},500);const v=JSON.stringify(project);if(history[hi]!==v){history=history.slice(0,hi+1);history.push(v);hi=history.length-1;history=history.slice(-80);hi=history.length-1;histBtns()}if(render)renderGame()}
function histBtns(){if(PLAY_ONLY)return;$('#undoBtn').disabled=hi<=0;$('#redoBtn').disabled=hi>=history.length-1}
function restore(i){if(i<0||i>=history.length)return;hi=i;project=JSON.parse(history[i]);ensure();sync();renderPlayers();renderQuestions();reset();histBtns()}
function sync(){if(PLAY_ONLY)return;ensure();const map={projectTitle:project.meta.title,localeSelect:project.locale,livesInput:project.lives,timerInput:project.timerSeconds,publicUrl:project.publicUrl||'',keeperDifficulty:project.keeperDifficulty,accentColor:project.theme.accent,cardColor:project.theme.card,textColor:project.theme.text,buttonColor:project.theme.button,questionSize:project.theme.questionSize,answerSize:project.theme.answerSize,cardOpacity:project.theme.cardOpacity};Object.entries(map).forEach(([id,v])=>{$('#'+id).value=v});$('#timerEnabled').checked=project.timerEnabled!==false;$('#soundEnabled').checked=project.soundEnabled!==false;$('#reducedMotion').checked=!!project.reducedMotion;$('#mathPreviewEnabled').checked=project.theme.mathPreview!==false;$('#questionSizeOut').value=project.theme.questionSize+'px';$('#answerSizeOut').value=project.theme.answerSize+'px';$('#cardOpacityOut').value=project.theme.cardOpacity+'%';$$('[data-mode-choice]').forEach(b=>b.classList.toggle('active',b.dataset.modeChoice===project.mode));$('#fieldMediaSettings').hidden=project.mode!=='field';$('#keeperMediaSettings').hidden=project.mode!=='keeper';mediaPreviews()}
function readControls(){project.meta.title=$('#projectTitle').value;project.locale=$('#localeSelect').value;project.lives=clamp(+$('#livesInput').value||3,1,20);project.timerSeconds=clamp(+$('#timerInput').value||180,15,3600);project.timerEnabled=$('#timerEnabled').checked;project.soundEnabled=$('#soundEnabled').checked;project.reducedMotion=$('#reducedMotion').checked;project.publicUrl=$('#publicUrl').value;project.keeperDifficulty=$('#keeperDifficulty').value;project.theme={...project.theme,accent:$('#accentColor').value,card:$('#cardColor').value,text:$('#textColor').value,button:$('#buttonColor').value,questionSize:+$('#questionSize').value,answerSize:+$('#answerSize').value,cardOpacity:+$('#cardOpacity').value,mathPreview:$('#mathPreviewEnabled').checked};sync();changed()}
function mediaPreviews(){[['fieldBackgroundPreview','fieldBackground','Фон не загружен'],['keeperBackgroundPreview','keeperBackground','Фон не загружен'],['keeperPreview','keeper','Вратарь не загружен'],['goalPreview','goal','Ворота не загружены']].forEach(([id,k,t])=>{const e=$('#'+id),s=project.media[k];e.style.backgroundImage=s?`url("${s}")`:'';e.textContent=s?'':t})}
function renderPlayers(){if(PLAY_ONLY)return;$('#playerList').innerHTML=project.players.map(p=>`<div class="player-upload-card"><div class="player-thumb" style="${p.asset?`background-image:url('${p.asset}')`:''}">${p.asset?'':'⚽'}</div><div><input class="player-name" data-id="${p.id}" maxlength="30" value="${esc(p.name)}"><label class="upload-file-btn">⬆ Загрузить изображение / GIF<input class="player-file" data-id="${p.id}" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label></div><div class="row-actions"><button data-clear="${p.id}">×</button></div></div>`).join('')}
function qActive(){return project.questions.find(q=>q.id===activeQ)}
function qValid(q){if(!q?.text?.trim())return false;if(q.type==='oral')return true;if(q.type==='text')return q.accepted?.some(a=>a.trim());if(q.type==='order')return q.options?.length>=2;return q.options?.length>=2&&q.options.some(o=>o.correct)}
function renderQuestions(){if(PLAY_ONLY)return;$('#questionList').innerHTML=project.questions.map((q,i)=>`<button class="question-chip ${q.id===activeQ?'active':''} ${qValid(q)?'':'invalid'}" data-q="${q.id}">${i+1}</button>`).join('')||'<span class="save-state">Пока нет заданий</span>';renderQEditor()}
function templates(){return `<div class="math-template-row"><button data-math="\\frac{a}{b}">Дробь</button><button data-math="x^{2}">Степень</button><button data-math="\\sqrt{x}">Корень</button><button data-math="x_{1}">Индекс</button><button data-math="\\sum_{i=1}^{n}">Сумма</button><button data-math="\\int_{a}^{b}">Интеграл</button></div>`}
function renderQEditor(){const q=qActive(),r=$('#questionEditor');if(!q){r.className='question-editor empty';r.innerHTML='<p>Выберите задание или добавьте новое.</p>';return}q.options||=[];q.accepted||=[];let d='';if(['single','multiple','order'].includes(q.type))d=`<div>${q.options.map((o,i)=>`<div class="option-row"><input class="correct-toggle" data-i="${i}" type="${q.type==='order'?'hidden':q.type==='multiple'?'checkbox':'radio'}" ${o.correct?'checked':''}><input class="option-text" data-i="${i}" value="${esc(o.text)}"><button class="remove-option" data-i="${i}">×</button></div>`).join('')}<button id="addOption" class="add-option">＋ Добавить вариант</button></div>`;if(q.type==='text')d=`<label>Допустимые ответы<textarea id="acceptedAnswers" rows="4">${esc(q.accepted.join('\n'))}</textarea></label>`;if(q.type==='oral')d='<div class="info-box">Устный ответ подтверждается кнопкой «Готово».</div>';r.className='question-editor';r.innerHTML=`<div class="editor-head"><h3>Задание</h3><div class="mini-actions"><button id="duplicateQuestion">⧉</button><button id="moveQuestionLeft">←</button><button id="moveQuestionRight">→</button><button id="deleteQuestion">🗑</button></div></div><label>Тип<select id="questionType"><option value="single">Один ответ</option><option value="multiple">Множественный выбор</option><option value="text">Ввод ответа</option><option value="oral">Устный ответ</option><option value="order">Расставить по порядку</option></select></label><label>Текст<textarea id="questionText" rows="3">${esc(q.text)}</textarea></label>${templates()}<div id="mathQuestionPreview" class="math-preview">${esc(q.text)}</div>${d}<div class="field-row"><label>Баллы<input id="questionPoints" type="number" value="${q.points||100}"></label><label>Подсказка<input id="questionHint" value="${esc(q.hint||'')}"></label></div><label>Пояснение<textarea id="questionExplanation" rows="2">${esc(q.explanation||'')}</textarea></label>`;$('#questionType').value=q.type;math($('#mathQuestionPreview'))}
