'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random()}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), norm=v=>String(v??'').trim().toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ');
const I18N=window.FOOTBALL_I18N||{}, PLAY_ONLY=!!window.FOOTBALL_PLAY_ONLY;
const POS=[[12,50],[27,20],[27,42],[27,65],[27,82],[48,24],[48,48],[48,72],[70,28],[70,52],[70,76]];
const player=i=>({id:uid(),name:`Игрок ${i+1}`,asset:'',x:POS[i]?.[0]??50,y:POS[i]?.[1]??50,size:90,questionId:null});
const question=()=>({id:uid(),type:'single',text:'Какой ответ верный?',options:[{id:uid(),text:'Первый вариант',correct:true},{id:uid(),text:'Второй вариант',correct:false},{id:uid(),text:'Третий вариант',correct:false}],accepted:['Ответ'],hint:'',explanation:'',points:100});
const defaults=()=>({schemaVersion:2,appVersion:'2.2.1',meta:{title:'Мой футбольный урок',author:'Гальмиз Мария Александровна'},locale:'ru',mode:'field',lives:3,timerEnabled:true,timerSeconds:180,soundEnabled:true,reducedMotion:false,publicUrl:'',keeperDifficulty:'normal',media:{fieldBackground:'',keeperBackground:'',keeper:'',goal:'',fieldKeeper:'',fieldKeeperX:88,fieldKeeperY:50,fieldKeeperSize:115,fieldMarkX:50,fieldMarkY:50,fieldMarkW:90,fieldMarkH:90,goalX:50,goalY:35,goalW:60,goalH:44,keeperX:50,keeperY:47,keeperSize:120,ballX:50,ballY:78,ballSize:42},players:Array.from({length:11},(_,i)=>player(i)),questions:[question()],theme:{accent:'#9cff58',card:'#102a22',text:'#ffffff',button:'#b7f34a',questionSize:28,answerSize:17,cardOpacity:92,mathPreview:true,questionFont:'Inter, sans-serif',answerFont:'Inter, sans-serif',inputBg:'#ffffff',glow:'soft'}});
let project=window.FOOTBALL_BOOT_PROJECT?window.FOOTBALL_BOOT_PROJECT:defaults(), activeQ=null, history=[], hi=0, saveTimer;
const G={running:false,ended:false,lives:3,time:180,points:0,goals:0,q:0,active:null,pending:null,task:false,selected:new Set(),order:[],feedback:'',locked:false,aim:null,timer:null,editPlayer:null,editFieldKeeper:false,editorTest:false,previewQuestionId:null};
function tr(k){return (I18N[project.locale]||I18N.en||{})[k]||k}
function ensure(){project={...defaults(),...project};project.meta={...defaults().meta,...project.meta};project.media={...defaults().media,...project.media};project.theme={...defaults().theme,...project.theme};project.players=Array.isArray(project.players)?project.players.slice(0,11):[];while(project.players.length<11)project.players.push(player(project.players.length));project.players.forEach((p,i)=>{p.id||=uid();p.name||=`Игрок ${i+1}`;p.asset||='';if(!Number.isFinite(p.x))p.x=POS[i]?.[0]??50;if(!Number.isFinite(p.y))p.y=POS[i]?.[1]??50;if(!Number.isFinite(p.size))p.size=90;p.size=clamp(+p.size||90,40,220);p.questionId||=null});project.questions=Array.isArray(project.questions)?project.questions:[];while(project.questions.length<project.players.length)project.questions.push(question());const usedQuestions=new Set();project.players.forEach((p,i)=>{if(!project.questions.some(q=>q.id===p.questionId)||usedQuestions.has(p.questionId))p.questionId=project.questions.find(q=>!usedQuestions.has(q.id))?.id||project.questions[i]?.id||project.questions[0]?.id||null;if(p.questionId)usedQuestions.add(p.questionId)});if(!Number.isFinite(project.media.fieldKeeperX))project.media.fieldKeeperX=88;if(!Number.isFinite(project.media.fieldKeeperY))project.media.fieldKeeperY=50;if(!Number.isFinite(project.media.fieldKeeperSize))project.media.fieldKeeperSize=115;project.media.fieldKeeperSize=clamp(+project.media.fieldKeeperSize||115,50,240);[['fieldMarkX',50],['fieldMarkY',50],['fieldMarkW',90],['fieldMarkH',90],['goalX',50],['goalY',35],['goalW',60],['goalH',44],['keeperX',50],['keeperY',47],['keeperSize',120],['ballX',50],['ballY',78],['ballSize',42]].forEach(([k,v])=>{if(!Number.isFinite(project.media[k]))project.media[k]=v});project.media.fieldMarkW=clamp(+project.media.fieldMarkW||90,20,100);project.media.fieldMarkH=clamp(+project.media.fieldMarkH||90,20,100);project.media.goalW=clamp(+project.media.goalW||60,15,100);project.media.goalH=clamp(+project.media.goalH||44,10,90);project.media.keeperSize=clamp(+project.media.keeperSize||120,40,260);project.media.ballSize=clamp(+project.media.ballSize||42,18,100);project.theme.questionFont||='Inter, sans-serif';project.theme.answerFont||='Inter, sans-serif';project.theme.inputBg||='#ffffff';project.theme.glow||='soft';project.mode=project.mode==='keeper'?'keeper':'field';project.lives=clamp(+project.lives||3,1,20);project.timerSeconds=clamp(+project.timerSeconds||180,15,3600);activeQ=project.questions.some(q=>q.id===activeQ)?activeQ:project.questions[0]?.id||null}
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function math(root=document){if(project.theme.mathPreview===false||typeof renderMathInElement!=='function')return;try{renderMathInElement(root,{delimiters:[{left:'$$',right:'$$',display:true},{left:'\\[',right:'\\]',display:true},{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false}],throwOnError:false,strict:'ignore'})}catch{}}
function changed(render=true){if(PLAY_ONLY)return;$('#saveState').textContent='Есть изменения';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('football-editor-draft-v2',JSON.stringify(project));$('#saveState').textContent='Сохранено локально'}catch{}},500);const v=JSON.stringify(project);if(history[hi]!==v){history=history.slice(0,hi+1);history.push(v);hi=history.length-1;history=history.slice(-80);hi=history.length-1;histBtns()}if(render)renderGame()}
function histBtns(){if(PLAY_ONLY)return;$('#undoBtn').disabled=hi<=0;$('#redoBtn').disabled=hi>=history.length-1}
function restore(i){if(i<0||i>=history.length)return;hi=i;project=JSON.parse(history[i]);ensure();sync();renderPlayers();reset();histBtns()}
function sync(){if(PLAY_ONLY)return;ensure();const map={projectTitle:project.meta.title,localeSelect:project.locale,livesInput:project.lives,timerInput:project.timerSeconds,publicUrl:project.publicUrl||'',keeperDifficulty:project.keeperDifficulty,accentColor:project.theme.accent,cardColor:project.theme.card,textColor:project.theme.text,buttonColor:project.theme.button,questionSize:project.theme.questionSize,answerSize:project.theme.answerSize,cardOpacity:project.theme.cardOpacity,questionFont:project.theme.questionFont,answerFont:project.theme.answerFont,inputBg:project.theme.inputBg,glowSelect:project.theme.glow,fieldMarkX:project.media.fieldMarkX,fieldMarkY:project.media.fieldMarkY,fieldMarkW:project.media.fieldMarkW,fieldMarkH:project.media.fieldMarkH,goalX:project.media.goalX,goalY:project.media.goalY,goalW:project.media.goalW,goalH:project.media.goalH,keeperX:project.media.keeperX,keeperY:project.media.keeperY,keeperSize:project.media.keeperSize,ballX:project.media.ballX,ballY:project.media.ballY,ballSize:project.media.ballSize};Object.entries(map).forEach(([id,v])=>{$('#'+id).value=v});$('#timerEnabled').checked=project.timerEnabled!==false;$('#soundEnabled').checked=project.soundEnabled!==false;$('#reducedMotion').checked=!!project.reducedMotion;$('#mathPreviewEnabled').checked=project.theme.mathPreview!==false;$('#questionSizeOut').value=project.theme.questionSize+'px';$('#answerSizeOut').value=project.theme.answerSize+'px';$('#cardOpacityOut').value=project.theme.cardOpacity+'%';$$('[data-mode-choice]').forEach(b=>b.classList.toggle('active',b.dataset.modeChoice===project.mode));$('#fieldMediaSettings').hidden=project.mode!=='field';$('#keeperMediaSettings').hidden=project.mode!=='keeper';mediaPreviews()}
function readControls(){project.meta.title=$('#projectTitle').value;project.locale=$('#localeSelect').value;project.lives=clamp(+$('#livesInput').value||3,1,20);project.timerSeconds=clamp(+$('#timerInput').value||180,15,3600);project.timerEnabled=$('#timerEnabled').checked;project.soundEnabled=$('#soundEnabled').checked;project.reducedMotion=$('#reducedMotion').checked;project.publicUrl=$('#publicUrl').value;project.keeperDifficulty=$('#keeperDifficulty').value;project.theme={...project.theme,accent:$('#accentColor').value,card:$('#cardColor').value,text:$('#textColor').value,button:$('#buttonColor').value,questionSize:+$('#questionSize').value,answerSize:+$('#answerSize').value,cardOpacity:+$('#cardOpacity').value,mathPreview:$('#mathPreviewEnabled').checked,questionFont:$('#questionFont').value,answerFont:$('#answerFont').value,inputBg:$('#inputBg').value,glow:$('#glowSelect').value};['fieldMarkX','fieldMarkY','fieldMarkW','fieldMarkH','goalX','goalY','goalW','goalH','keeperX','keeperY','keeperSize','ballX','ballY','ballSize'].forEach(id=>project.media[id]=+$('#'+id).value);sync();changed()}
function mediaPreviews(){[['fieldBackgroundPreview','fieldBackground','Фон не загружен'],['fieldKeeperPreview','fieldKeeper','Вратарь соперника не загружен'],['keeperBackgroundPreview','keeperBackground','Фон не загружен'],['keeperPreview','keeper','Вратарь не загружен'],['goalPreview','goal','Ворота не загружены']].forEach(([id,k,t])=>{const e=$('#'+id),s=project.media[k];e.style.backgroundImage=s?`url("${s}")`:'';e.textContent=s?'':t})}
function renderPlayers(){if(PLAY_ONLY)return;$('#playerList').innerHTML=project.players.map((p,i)=>{const q=project.questions.find(x=>x.id===p.questionId)||project.questions[i];return `<details class="player-upload-card" data-player-card="${p.id}" ${G.editPlayer===p.id?'open':''}><summary><div class="player-thumb" style="${p.asset?`background-image:url('${p.asset}')`:''}">${p.asset?'':'⚽'}</div><div><b>${esc(p.name)}</b><small>Игрок ${i+1} · ${q?esc(q.text).slice(0,42):'без задания'}</small></div><span>▾</span></summary><div class="player-card-body"><input class="player-name" data-id="${p.id}" maxlength="30" value="${esc(p.name)}"><label class="upload-file-btn">⬆ Загрузить изображение / GIF<input class="player-file" data-id="${p.id}" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><div class="inline-task" data-inline-task="${p.id}">${q?renderInlineTask(q,p.id):''}</div><div class="row-actions"><button data-edit-player="${p.id}">Показать на поле</button><button data-clear="${p.id}">Очистить игрока</button></div></div></details>`}).join('')}
function qActive(){return project.questions.find(q=>q.id===activeQ)}
function renderInlineTask(q,pid){q.options||=[];q.accepted||=[];let body='';if(['single','multiple','order'].includes(q.type))body=`<div class="inline-options">${q.options.map((o,i)=>`<div class="inline-option"><input class="inline-correct" data-player="${pid}" data-i="${i}" type="${q.type==='order'?'hidden':q.type==='multiple'?'checkbox':'radio'}" ${o.correct?'checked':''}><input class="inline-option-text" data-player="${pid}" data-i="${i}" value="${esc(o.text)}"></div>`).join('')}</div>`;if(q.type==='text')body=`<label>Допустимые ответы<textarea class="inline-accepted" data-player="${pid}" rows="3">${esc(q.accepted.join('\n'))}</textarea></label>`;if(q.type==='oral')body='<div class="info-box">Устный ответ подтверждается кнопкой «Готово».</div>';return `<label>Тип задания<select class="inline-type" data-player="${pid}"><option value="single" ${q.type==='single'?'selected':''}>Один ответ</option><option value="multiple" ${q.type==='multiple'?'selected':''}>Множественный выбор</option><option value="text" ${q.type==='text'?'selected':''}>Ввод ответа</option><option value="oral" ${q.type==='oral'?'selected':''}>Устный ответ</option><option value="order" ${q.type==='order'?'selected':''}>Расставить по порядку</option></select></label><label>Текст задания<textarea class="inline-question" data-player="${pid}" rows="3">${esc(q.text)}</textarea></label>${body}<button class="add-inline-option" data-player="${pid}" type="button">＋ Добавить вариант</button>`}
function qValid(q){if(!q?.text?.trim())return false;if(q.type==='oral')return true;if(q.type==='text')return q.accepted?.some(a=>a.trim());if(q.type==='order')return q.options?.length>=2;return q.options?.length>=2&&q.options.some(o=>o.correct)}
function renderQuestions(){if(PLAY_ONLY||!$('#questionList'))return;$('#questionList').innerHTML=project.questions.map((q,i)=>`<button class="question-chip ${q.id===activeQ?'active':''} ${qValid(q)?'':'invalid'}" data-q="${q.id}">${i+1}</button>`).join('')||'<span class="save-state">Пока нет заданий</span>';renderQEditor()}
function templates(){return `<div class="math-template-row"><button data-math="\\frac{a}{b}">Дробь</button><button data-math="x^{2}">Степень</button><button data-math="\\sqrt{x}">Корень</button><button data-math="x_{1}">Индекс</button><button data-math="\\sum_{i=1}^{n}">Сумма</button><button data-math="\\int_{a}^{b}">Интеграл</button></div>`}
function renderQEditor(){const q=qActive(),r=$('#questionEditor');if(!r)return;if(!q){r.className='question-editor empty';r.innerHTML='<p>Выберите задание или добавьте новое.</p>';return}q.options||=[];q.accepted||=[];let d='';if(['single','multiple','order'].includes(q.type))d=`<div>${q.options.map((o,i)=>`<div class="option-row"><input class="correct-toggle" data-i="${i}" type="${q.type==='order'?'hidden':q.type==='multiple'?'checkbox':'radio'}" ${o.correct?'checked':''}><input class="option-text" data-i="${i}" value="${esc(o.text)}"><button class="remove-option" data-i="${i}">×</button></div>`).join('')}<button id="addOption" class="add-option">＋ Добавить вариант</button></div>`;if(q.type==='text')d=`<label>Допустимые ответы<textarea id="acceptedAnswers" rows="4">${esc(q.accepted.join('\n'))}</textarea></label>`;if(q.type==='oral')d='<div class="info-box">Устный ответ подтверждается кнопкой «Готово».</div>';r.className='question-editor';r.innerHTML=`<div class="editor-head"><h3>Задание</h3><div class="mini-actions"><button id="duplicateQuestion">⧉</button><button id="moveQuestionLeft">←</button><button id="moveQuestionRight">→</button><button id="deleteQuestion">🗑</button></div></div><label>Тип<select id="questionType"><option value="single">Один ответ</option><option value="multiple">Множественный выбор</option><option value="text">Ввод ответа</option><option value="oral">Устный ответ</option><option value="order">Расставить по порядку</option></select></label><label>Текст<textarea id="questionText" rows="3">${esc(q.text)}</textarea></label>${templates()}<div id="mathQuestionPreview" class="math-preview">${esc(q.text)}</div>${d}<div class="field-row"><label>Баллы<input id="questionPoints" type="number" value="${q.points||100}"></label><label>Подсказка<input id="questionHint" value="${esc(q.hint||'')}"></label></div><label>Пояснение<textarea id="questionExplanation" rows="2">${esc(q.explanation||'')}</textarea></label>`;$('#questionType').value=q.type;math($('#mathQuestionPreview'))}
