'use strict';
function qInput(e){const q=qActive(),x=e.target;if(!q||!$('#questionEditor'))return;if(x.id==='questionType'){q.type=x.value;if(q.type==='order')q.options.forEach(o=>o.correct=false);renderQEditor()}else if(x.id==='questionText'){q.text=x.value;$('#mathQuestionPreview').textContent=q.text;math($('#mathQuestionPreview'))}else if(x.id==='questionPoints')q.points=+x.value||0;else if(x.id==='questionHint')q.hint=x.value;else if(x.id==='questionExplanation')q.explanation=x.value;else if(x.id==='acceptedAnswers')q.accepted=x.value.split('\n').filter(Boolean);else if(x.classList.contains('option-text'))q.options[+x.dataset.i].text=x.value;else if(x.classList.contains('correct-toggle')){if(q.type==='single')q.options.forEach((o,i)=>o.correct=i===+x.dataset.i);else q.options[+x.dataset.i].correct=x.checked;renderQEditor()}changed(false);if(G.previewQuestionId===q.id){G.task=true;renderGame()}}
function qClick(e){const q=qActive();if(!q)return;const m=e.target.closest('[data-math]');if(m){const t=$('#questionText'),ins=`$${m.dataset.math}$`,a=t.selectionStart??t.value.length,b=t.selectionEnd??a;t.value=t.value.slice(0,a)+ins+t.value.slice(b);q.text=t.value;renderQEditor();changed();return}if(e.target.id==='addOption'){q.options.push({id:uid(),text:`Вариант ${q.options.length+1}`,correct:false});renderQEditor();changed();return}const rm=e.target.closest('.remove-option');if(rm){q.options.splice(+rm.dataset.i,1);renderQEditor();changed();return}if(e.target.id==='deleteQuestion'){project.questions=project.questions.filter(x=>x.id!==q.id);project.players.forEach(p=>{if(p.questionId===q.id)p.questionId=null});ensure();activeQ=fieldQuestions()[0]?.id||null;renderPlayers();renderQuestions();changed();return}if(e.target.id==='duplicateQuestion'){const c=JSON.parse(JSON.stringify(q));c.id=uid();c.options=c.options.map(o=>({...o,id:uid()}));project.questions.splice(project.questions.indexOf(q)+1,0,c);activeQ=c.id;renderQuestions();changed();return}if(e.target.id==='moveQuestionLeft'||e.target.id==='moveQuestionRight'){const i=project.questions.indexOf(q),j=i+(e.target.id.endsWith('Left')?-1:1);if(j>=0&&j<project.questions.length)[project.questions[i],project.questions[j]]=[project.questions[j],project.questions[i]];renderQuestions();changed()}}
function selectPlayerForEdit(id){const p=project.players.find(x=>x.id===id);if(!p)return;G.editPlayer=id;G.editFieldKeeper=false;G.task=false;G.previewQuestionId=null;$$('.editor-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='players'));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel==='players'));renderPlayers();renderGame();requestAnimationFrame(()=>document.querySelector('[data-player-card="'+CSS.escape(id)+'"]')?.scrollIntoView({block:'nearest'}))}
function safeName(){return(project.meta.title||'football-game').trim().replace(/[^a-zа-яё0-9_-]+/gi,'-').replace(/^-|-$/g,'')||'football-game'}
function dl(content,name,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportHtml(){const p=JSON.stringify(project).replace(/</g,'\\u003c');return `<!doctype html><html lang="${project.locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(project.meta.title)}</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"><link rel="stylesheet" href="https://galmizmaria-beep.github.io/futbol/base.css?v=2.5.0"><link rel="stylesheet" href="https://galmizmaria-beep.github.io/futbol/gameplay.css?v=2.5.0"><style>html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#071a13}body{display:block!important;min-height:0!important}#game.game-shell{width:100vw!important;height:100vh!important;min-height:0!important;max-width:none!important;aspect-ratio:auto!important;border:0!important;border-radius:0!important;box-shadow:none!important}</style></head><body><div id="game" class="game-shell"></div><script>window.FOOTBALL_PLAY_ONLY=true;window.FOOTBALL_BOOT_PROJECT=${p};<\/script><script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"><\/script><script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"><\/script><script src="https://galmizmaria-beep.github.io/futbol/i18n.js?v=2.5.0"><\/script><script src="https://galmizmaria-beep.github.io/futbol/core.js?v=2.5.0"><\/script><script src="https://galmizmaria-beep.github.io/futbol/game.js?v=2.5.0"><\/script><script src="https://galmizmaria-beep.github.io/futbol/editor.js?v=2.5.0"><\/script></body></html>`}
function loadProject(e){const f=e.target.files?.[0];if(!f)return;f.text().then(t=>{project=JSON.parse(t);ensure();activeQ=project.questions[0]?.id||null;history=[JSON.stringify(project)];hi=0;sync();renderPlayers();renderQuestions();renderKeeperTaskEditor();reset();toast('Проект загружен')}).catch(x=>toast('Ошибка: '+x.message));e.target.value=''}
function renderKeeperTaskEditor(){if(PLAY_ONLY)return;const box=$('#keeperTaskEditor'),list=keeperQuestions();if(!box)return;box.innerHTML=`<div class="keeper-task-list">${list.map((q,i)=>`<details class="keeper-task-item" ${G.keeperEditIndex===i?'open':''}><summary>Задание ${i+1}: ${esc(q.text).slice(0,42)}</summary><div class="keeper-task-body">${renderInlineTask(q,'keeper:'+i)}<button class="delete-keeper-task" data-keeper-index="${i}" type="button">Удалить задание</button></div></details>`).join('')}</div><button id="addKeeperTask" type="button">＋ Добавить задание</button>`}
function inlineTaskInput(e){
  const pid=e.target.dataset.player;if(!pid)return;const keeperMatch=pid.match(/^keeper:(\d+)$/),keeperIndex=keeperMatch?+keeperMatch[1]:null;
  const p=keeperMatch?null:project.players.find(x=>x.id===pid),q=keeperMatch?keeperQuestion(keeperIndex):project.questions.find(x=>x.id===p?.questionId);if(!q||(!p&&!keeperMatch))return;
  activeQ=q.id;G.editPlayer=keeperMatch?null:pid;G.keeperEditIndex=keeperIndex;G.previewQuestionId=q.id;G.task=true;
  const x=e.target;
  if(x.classList.contains('inline-type')){q.type=x.value;if(q.type==='order')q.options.forEach(o=>o.correct=false);keeperMatch?renderKeeperTaskEditor():renderPlayers()}
  else if(x.classList.contains('inline-question'))q.text=x.value;
  else if(x.classList.contains('inline-option-text'))q.options[+x.dataset.i].text=x.value;
  else if(x.classList.contains('inline-accepted'))q.accepted=x.value.split('\n').filter(Boolean);
  else if(x.classList.contains('inline-correct')){if(q.type==='single')q.options.forEach((o,i)=>o.correct=i===+x.dataset.i);else q.options[+x.dataset.i].correct=x.checked}
  changed(false);renderGame()
}
function bindEditor(){if(PLAY_ONLY)return;
  $$('.editor-tabs button').forEach(b=>b.onclick=()=>{$$('.editor-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))});
  $$('[data-mode-choice]').forEach(b=>b.onclick=()=>{project.mode=b.dataset.modeChoice;G.task=false;G.previewQuestionId=null;sync();if(project.mode==='keeper')renderKeeperTaskEditor();reset();changed()});
  const controlIds=['projectTitle','localeSelect','livesInput','timerInput','timerEnabled','soundEnabled','reducedMotion','publicUrl','keeperDifficulty','accentColor','cardColor','textColor','buttonColor','questionSize','answerSize','cardOpacity','mathPreviewEnabled','questionFont','answerFont','inputBg','glowSelect','fieldMarkX','fieldMarkY','fieldMarkW','fieldMarkH','goalX','goalY','goalW','goalH','keeperX','keeperY','keeperSize','ballX','ballY','ballSize'];
  controlIds.forEach(id=>{const el=$('#'+id);if(el)el.addEventListener(['localeSelect','timerEnabled','soundEnabled','reducedMotion','keeperDifficulty','mathPreviewEnabled'].includes(id)?'change':'input',readControls)});
  [['fieldBackgroundFile','fieldBackground'],['fieldKeeperFile','fieldKeeper'],['keeperBackgroundFile','keeperBackground'],['keeperFile','keeper'],['goalFile','goal']].forEach(([id,k])=>$('#'+id).onchange=e=>mediaInput(e.target,k));
  const keeperEditor=$('#keeperTaskEditor');if(keeperEditor){keeperEditor.oninput=inlineTaskInput;keeperEditor.onchange=inlineTaskInput;keeperEditor.onclick=e=>{const addTask=e.target.closest('#addKeeperTask');if(addTask){const q=question();project.questions.push(q);project.keeperQuestionIds.push(q.id);G.keeperEditIndex=project.keeperQuestionIds.length-1;G.previewQuestionId=q.id;G.task=true;renderKeeperTaskEditor();renderGame();changed(false);return}const del=e.target.closest('.delete-keeper-task');if(del){const i=+del.dataset.keeperIndex,id=project.keeperQuestionIds[i];if(project.keeperQuestionIds.length>1){project.keeperQuestionIds.splice(i,1);project.questions=project.questions.filter(q=>q.id!==id);G.keeperEditIndex=Math.max(0,i-1);renderKeeperTaskEditor();changed();}else toast('В режиме вратаря должно остаться хотя бы одно задание.');return}const add=e.target.closest('.add-inline-option');if(add){const m=(add.dataset.player||'').match(/^keeper:(\d+)$/),q=m?keeperQuestion(+m[1]):null;if(q){q.options.push({id:uid(),text:'Новый вариант',correct:false});G.keeperEditIndex=+m[1];G.previewQuestionId=q.id;G.task=true;renderKeeperTaskEditor();renderGame();changed(false)}}}}
  $('#playerList').oninput=e=>{if(e.target.classList.contains('player-name')){const p=project.players.find(p=>p.id===e.target.dataset.id);if(p){p.name=e.target.value;changed(false);renderGame()}}};
  $('#playerList').onchange=e=>{if(e.target.classList.contains('player-file'))playerInput(e.target,e.target.dataset.id)};
  $('#playerList').onclick=e=>{
    const edit=e.target.closest('[data-edit-player]');if(edit){selectPlayerForEdit(edit.dataset.editPlayer);return}
    const clear=e.target.closest('[data-clear]');if(clear){const p=project.players.find(p=>p.id===clear.dataset.clear);if(p){p.asset='';G.editPlayer=clear.dataset.clear;renderPlayers();renderGame();changed(false)}}
  };
  $('#questionList').onclick=e=>{const b=e.target.closest('[data-q]');if(b){activeQ=b.dataset.q;G.previewQuestionId=activeQ;G.task=true;renderQuestions();renderGame()}};
  $('#addQuestion').onclick=()=>{const q=question();project.questions.push(q);activeQ=q.id;G.previewQuestionId=q.id;G.task=true;renderQuestions();renderGame();changed(false)};
  $('#questionEditor').addEventListener('input',qInput);$('#questionEditor').addEventListener('change',qInput);$('#questionEditor').onclick=qClick;
  $('#addPlayer').onclick=()=>toast('В составе уже доступно 11 игроков.');
  $('#testGame').onclick=()=>{G.editorTest=!G.editorTest;G.editPlayer=null;G.editFieldKeeper=false;G.previewQuestionId=null;G.task=false;$('#testGame').textContent=G.editorTest?'✎ Вернуться к редактированию':'▶ Тест игры';$('#testGame').classList.toggle('active',G.editorTest);reset()};
  $('#restartPreview').onclick=()=>reset();$('#undoBtn').onclick=()=>restore(hi-1);$('#redoBtn').onclick=()=>restore(hi+1);
  $('#newBtn').onclick=()=>{if(confirm('Создать новый проект?')){localStorage.removeItem('football-editor-draft-v2');project=defaults();ensure();activeQ=project.questions[0].id;history=[JSON.stringify(project)];hi=0;sync();renderPlayers();renderQuestions();renderKeeperTaskEditor();reset()}};
  $('#saveBtn').onclick=()=>dl(JSON.stringify(project,null,2),safeName()+'.football-project.json','application/json');$('#loadBtn').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=loadProject;$('#htmlBtn').onclick=()=>dl(exportHtml(),safeName()+'.html','text/html');
  const show=()=>{$('#dialogTitle').textContent='Код для Genially';$('#dialogText').textContent='Вставьте этот iframe в Genially. Игра заполняет весь контейнер без внутренних рамок редактора.';$('#exportCode').value=`<iframe srcdoc="${exportHtml().replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}" style="display:block;width:100%;height:100%;border:0;margin:0;padding:0;background:transparent" allowfullscreen></iframe>`;$('#exportDialog').showModal()};
  $('#minifyBtn').onclick=show;$('#embedBtn').onclick=show;$('#downloadLight').onclick=()=>dl(exportHtml().replace(/\n\s*/g,''),safeName()+'-light.html','text/html');$('#copyCode').onclick=async()=>{await navigator.clipboard.writeText($('#exportCode').value);$('#copyStatus').textContent='Код скопирован'};$('.dialog-close').onclick=()=>$('#exportDialog').close();
  $$('.preview-toolbar [data-scale]').forEach(b=>b.onclick=()=>{$$('.preview-toolbar [data-scale]').forEach(x=>x.classList.toggle('active',x===b));$('#game').style.transform=`scale(${b.dataset.scale})`});$('#fullscreenBtn').onclick=()=>$('#game').requestFullscreen?.();
  $$('.mobile-switch button').forEach(b=>b.onclick=()=>{document.body.dataset.mobileView=b.dataset.view;$$('.mobile-switch button').forEach(x=>x.classList.toggle('active',x===b))});document.body.dataset.mobileView='editor';document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();restore(hi+(e.shiftKey?1:-1))}})
}
ensure();if(!PLAY_ONLY){sync();renderPlayers();renderQuestions();renderKeeperTaskEditor();history=[JSON.stringify(project)];bindEditor();histBtns();const saved=localStorage.getItem('football-editor-draft-v2');if(saved){const dlg=$('#resumeDialog');if(dlg){dlg.showModal();$('#resumeProject').onclick=()=>{try{project=JSON.parse(saved);ensure();sync();renderPlayers();renderQuestions();renderKeeperTaskEditor();reset();history=[JSON.stringify(project)];hi=0;histBtns()}catch{}dlg.close()};$('#resetProject').onclick=()=>{localStorage.removeItem('football-editor-draft-v2');project=defaults();ensure();sync();renderPlayers();renderQuestions();renderKeeperTaskEditor();reset();history=[JSON.stringify(project)];hi=0;histBtns();dlg.close()}}}}$('#game').addEventListener('click',gameClick);if(!PLAY_ONLY)$('#game').addEventListener('pointerdown',e=>{const rp=e.target.closest('[data-resize-player]');if(rp){resizePlayerStart(e,rp.dataset.resizePlayer);return}const rk=e.target.closest('[data-resize-field-keeper]');if(rk){resizeFieldKeeperStart(e);return}const fk=e.target.closest('[data-field-keeper]');if(fk){G.editFieldKeeper=true;G.editPlayer=null;dragFieldKeeperStart(e);return}const p=e.target.closest('[data-player]');if(p&&editorMode()){G.editPlayer=p.dataset.player;G.editFieldKeeper=false;dragStart(e,p.dataset.player)}});reset();
