'use strict';
function stopTimer(){clearInterval(G.timer);G.timer=null}function startTimer(){stopTimer();if(project.timerEnabled)G.timer=setInterval(()=>{if(!G.running||G.ended)return;G.time=Math.max(0,G.time-1);hud();if(!G.time)finish()},1000)}
function reset(render=true){stopTimer();Object.assign(G,{running:false,ended:false,lives:project.lives,time:project.timerSeconds,points:0,goals:0,q:0,active:project.players[0]?.id||null,pending:null,task:false,selected:new Set(),order:[],feedback:'',locked:false,aim:null});if(render)renderGame()}
function start(render=true){if(G.ended)reset(false);G.running=true;startTimer();if(render)renderGame()}
function finish(){G.running=false;G.ended=true;G.task=false;stopTimer();renderGame()}
function lose(){G.lives=Math.max(0,G.lives-1);if(!G.lives){finish();return true}return false}
function fmt(s){return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}function hud(){const a=$('[data-lives]'),b=$('[data-time]');if(a)a.textContent='♥ '+G.lives;if(b)b.textContent=fmt(G.time)}
function renderGame(){const r=$('#game');r.dir=project.locale==='ar'?'rtl':'ltr';r.classList.toggle('reduced',project.reducedMotion);[['--accent',project.theme.accent],['--card',project.theme.card],['--gameText',project.theme.text],['--button',project.theme.button],['--qsize',project.theme.questionSize+'px'],['--asize',project.theme.answerSize+'px'],['--cardOpacity',project.theme.cardOpacity/100]].forEach(([k,v])=>r.style.setProperty(k,v));const bg=project.mode==='field'?project.media.fieldBackground:project.media.keeperBackground;let body=G.ended?endMarkup():(project.mode==='field'?fieldMarkup():keeperMarkup());r.innerHTML=`<div class="game-bg" style="${bg?`background-image:url('${bg}')`:''}"></div><header class="game-top"><div class="game-logo">⚽ ${esc(project.meta.title)}</div><div class="game-spacer"></div><div class="hud"><span class="hud-pill">${tr('lives')}: <b data-lives>♥ ${G.lives}</b></span>${project.timerEnabled?`<span class="hud-pill">${tr('time')}: <b data-time>${fmt(G.time)}</b></span>`:''}<span class="hud-pill">${tr('points')}: <b>${G.points}</b></span><span class="hud-pill">${tr('goals')}: <b>${G.goals}</b></span></div></header><main class="game-content">${body}${G.task?taskMarkup():''}</main>`;math(r);if(project.mode==='keeper'&&!G.ended)requestAnimationFrame(bindAim)}
function endMarkup(){return `<section class="end-screen"><div class="glass-card"><h1>${G.lives?tr('win'):tr('lose')}</h1><p>${tr('goals')}: <b>${G.goals}</b> · ${tr('points')}: <b>${G.points}</b></p><button class="game-button" data-act="restart">${tr('again')}</button></div></section>`}
function fieldMarkup(){const a=project.players.find(p=>p.id===G.active)||project.players[0];return `<section class="field-mode" id="fieldSurface"><div class="center-circle"></div>${project.players.map(p=>`<button class="field-player ${p.id===G.active?'active':''}" data-player="${p.id}" style="left:${p.x}%;top:${p.y}%">${p.asset?`<img src="${p.asset}" alt="">`:'<span class="fallback-player">⚽</span>'}<span class="player-label">${esc(p.name)}</span>${PLAY_ONLY?'':`<i class="drag-handle" data-drag="${p.id}">■</i>`}</button>`).join('')}<div class="ball-on-field" style="left:${a?.x??50}%;top:${(a?.y??50)+6}%">⚽</div><div class="pass-hint">${G.running?tr('chooseTarget'):tr('passHint')} ${G.running?'':`· <button class="game-button" data-act="start">${tr('start')}</button>`}</div></section>`}
function keeperMarkup(){return `<section class="keeper-mode" id="keeperSurface">${project.media.goal?`<img class="goal-image" src="${project.media.goal}" alt="">`:'<div class="goal-css"></div>'}${project.media.keeper?`<img class="keeper-image" id="keeperSprite" src="${project.media.keeper}" alt="">`:'<div class="keeper-css" id="keeperSprite"></div>'}<div class="keeper-ball" id="keeperBall">⚽</div><div id="aimLine" class="aim-line" hidden></div><div class="keeper-hint">${tr('aimHint')} ${G.running?'':`· <button class="game-button" data-act="start">${tr('start')}</button>`}</div></section>`}
function curQ(){return project.questions.length?project.questions[G.q%project.questions.length]:null}
function taskMarkup(){const q=curQ();if(!q)return `<div class="task-overlay"><section class="task-card">${tr('noQuestions')}</section></div>`;let b='';if(['single','multiple'].includes(q.type))b=`<div class="answers">${q.options.map(o=>`<button class="answer-btn ${G.selected.has(o.id)?'selected':''}" data-answer="${o.id}">${esc(o.text)}</button>`).join('')}</div>`;else if(q.type==='text')b=`<input id="runtimeTextAnswer" class="text-answer" placeholder="${esc(tr('typeAnswer'))}">`;else if(q.type==='oral')b=`<p>${esc(tr('oral'))}</p>`;else{if(!G.order.length)G.order=q.options.map(o=>o.id).sort(()=>Math.random()-.5);b=`<p>${esc(tr('order'))}</p><div class="sort-list">${G.order.map((id,i)=>`<div class="sort-item"><span>${esc(q.options.find(o=>o.id===id)?.text||'')}</span><button data-up="${i}">↑</button><button data-down="${i}">↓</button></div>`).join('')}</div>`}return `<div class="task-overlay"><section class="task-card"><div class="task-head"><span>${tr('question')} ${G.q%project.questions.length+1}/${project.questions.length}</span><span>+${q.points||100}</span></div><h2>${esc(q.text)}</h2>${b}${q.hint?`<p class="panel-note">💡 ${esc(q.hint)}</p>`:''}<div class="task-actions"><span class="feedback ${G.feedback}">${G.feedback==='ok'?tr('correct'):G.feedback==='bad'?tr('incorrect'):''}</span><button class="game-button" data-act="submit" ${G.locked?'disabled':''}>${q.type==='oral'?tr('ready'):tr('submit')}</button></div></section></div>`}
function openTask(p){if(!G.running)start(false);G.pending=p;if(!project.questions.length){resolve(true);return}G.selected=new Set();G.order=[];G.feedback='';G.locked=false;G.task=true;renderGame()}
function checkTask(){const q=curQ();if(!q||G.locked)return;let ok=false;if(q.type==='oral')ok=true;else if(q.type==='text')ok=(q.accepted||[]).some(a=>norm(a)===norm($('#runtimeTextAnswer')?.value));else if(q.type==='order')ok=G.order.every((id,i)=>id===q.options[i]?.id);else ok=[...G.selected].sort().join('|')===q.options.filter(o=>o.correct).map(o=>o.id).sort().join('|')&&G.selected.size>0;G.locked=true;G.feedback=ok?'ok':'bad';if(ok)G.points+=q.points||100;else if(lose())return;renderGame();tone(ok);setTimeout(()=>{G.task=false;G.q++;resolve(ok)},600)}
function resolve(ok){const p=G.pending;G.pending=null;if(p?.type==='pass'){if(ok)G.active=p.to;renderGame()}else if(p?.type==='shot')shot(ok,p);else renderGame()}
function bindAim(){const s=$('#keeperSurface'),b=$('#keeperBall');if(!s||!b||b._bound)return;b._bound=1;b.onpointerdown=e=>{e.preventDefault();if(!G.running)start(false);const r=s.getBoundingClientRect();G.aim={};b.setPointerCapture?.(e.pointerId);aimMove(e,r)};b.onpointermove=e=>{if(G.aim)aimMove(e,s.getBoundingClientRect())};b.onpointerup=e=>{if(!G.aim)return;const r=s.getBoundingClientRect();const x=clamp((e.clientX-r.left)/r.width*100,22,78),y=clamp((e.clientY-r.top)/r.height*100,15,58);G.aim=null;openTask({type:'shot',x,y})}}
function aimMove(e,r){const l=$('#aimLine'),b=$('#keeperBall').getBoundingClientRect(),sx=b.left+b.width/2-r.left,sy=b.top+b.height/2-r.top,dx=e.clientX-r.left-sx,dy=e.clientY-r.top-sy;l.hidden=false;l.style.cssText+=`;left:${sx}px;top:${sy}px;width:${Math.hypot(dx,dy)}px;transform:rotate(${Math.atan2(dy,dx)}rad)`}
function shot(correct,p){renderGame();const b=$('#keeperBall'),k=$('#keeperSprite');if(!b||!k)return;const saved=!correct||Math.random()<({easy:.15,normal:.32,hard:.5}[project.keeperDifficulty]??.32);k.style.left=clamp(p.x+(Math.random()-.5)*18,25,75)+'%';b.style.transition='left .55s,top .55s,transform .55s';b.style.left=p.x+'%';b.style.top=p.y+'%';b.style.transform='translate(-50%,-50%) scale(.58)';setTimeout(()=>{if(!saved){G.goals++;G.points+=50}$('#game').insertAdjacentHTML('beforeend',`<div class="result-flash">${esc(saved?tr('saved'):tr('goal'))}</div>`);tone(!saved);setTimeout(renderGame,650)},560)}
function tone(ok){if(!project.soundEnabled)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?660:190;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}
function dragStart(e,id){e.preventDefault();e.stopPropagation();const s=$('#fieldSurface'),el=$(`[data-player="${CSS.escape(id)}"]`);if(!s||!el)return;const move=ev=>{const r=s.getBoundingClientRect(),p=project.players.find(x=>x.id===id);p.x=clamp((ev.clientX-r.left)/r.width*100,5,95);p.y=clamp((ev.clientY-r.top)/r.height*100,8,92);el.style.left=p.x+'%';el.style.top=p.y+'%';if(G.active===id){const b=$('.ball-on-field');b.style.left=p.x+'%';b.style.top=(p.y+6)+'%'}};const up=()=>{document.removeEventListener('pointermove',move);changed(false)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true})}
function gameClick(e){const a=e.target.closest('[data-act]')?.dataset.act;if(a==='start'){start();return}if(a==='restart'){reset();return}if(a==='submit'){checkTask();return}const an=e.target.closest('[data-answer]');if(an&&!G.locked){const q=curQ();if(q.type==='single')G.selected=new Set([an.dataset.answer]);else G.selected.has(an.dataset.answer)?G.selected.delete(an.dataset.answer):G.selected.add(an.dataset.answer);renderGame();return}const u=e.target.closest('[data-up]'),d=e.target.closest('[data-down]');if(u||d){const i=+(u?.dataset.up??d.dataset.down),j=i+(u?-1:1);if(j>=0&&j<G.order.length)[G.order[i],G.order[j]]=[G.order[j],G.order[i]];renderGame();return}if(e.target.closest('[data-drag]'))return;const p=e.target.closest('[data-player]');if(p&&!G.task&&p.dataset.player!==G.active){openTask({type:'pass',to:p.dataset.player})}}
async function toData(file,max=1600,q=.82){if(file.size>12*1024*1024)throw Error('Файл больше 12 МБ');if(file.type==='image/gif')return fileData(file);const src=await fileData(file),img=await new Promise((res,rej)=>{const i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=src}),scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/webp',q)}
function fileData(f){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
async function mediaInput(inp,key){const f=inp.files?.[0];if(!f)return;try{project.media[key]=await toData(f,key.includes('Background')?1800:1000);if(f.type==='image/gif')toast('GIF сохранён с анимацией; статичные изображения сжимаются автоматически.');sync();changed()}catch(e){toast(e.message)}inp.value=''}
async function playerInput(inp,id){const f=inp.files?.[0];if(!f)return;try{project.players.find(p=>p.id===id).asset=await toData(f,900,.8);if(f.type==='image/gif')toast('GIF сохранён с анимацией.');renderPlayers();changed()}catch(e){toast(e.message)}inp.value=''}
